### ISSUE TITLE
Bug in compute_ious

### ISSUE THREAD

**Issue by islam-nassar** [usnistgov/ccu_validation_scoring#1]
Hi there, 

I hit a bug while trying to evaluate our system. [Here](https://github.com/usnistgov/ccu_validation_scoring/blob/3aa15d0d9ef090a321e5b69ad366a8e4fe1e7b82/CCU_validation_scoring/score_norm_emotion.py#L80), if `ref` dataframe is empty, the return value does not include "type". However, [here](https://github.com/usnistgov/ccu_validation_scoring/blob/3aa15d0d9ef090a321e5b69ad366a8e4fe1e7b82/CCU_validation_scoring/score_norm_emotion.py#L213), it is expected to have "type" so it throws an error. To fix this, I just edited L80 to the following:

`        return pd.DataFrame(data=[[row.Class, row.type, row.file_id, np.nan, np.nan, row.start, row.end, row.llr, 0.0]],
            columns=['Class', 'type', 'file_id', 'start_ref', 'end_ref', 'start_hyp', 'end_hyp', 'llr', 'IoU'])`

**Comment by jfiscus** [comment]
Thanks for the report.  I've fixed this in the upcoming release.  The commit id is 3c12a5660fb42b8765bb2edf74e2e5525b792d4b.
