### ISSUE TITLE
please remove print statement

### ISSUE THREAD

**Issue by islam-nassar** [usnistgov/ccu_validation_scoring#10]
Can you please remove the print statement in [L332](https://github.com/usnistgov/ccu_validation_scoring/blob/d45b14dadfa8370545bcd9f1f124aba1a7aef113/CCU_validation_scoring/score_norm_emotion.py#L332)? It floods the stdout when running on large dataset.

**Comment by jfiscus** [comment]
Fixed in commit bc6c1491995d524fd12dc206fbeb9a8b5ec4da87.
