### ISSUE TITLE
How to install Scorer Version 1.1.0   ERROR: Could not find a version that satisfies the requirement subprocess 

### ISSUE THREAD

**Issue by yrf1** [usnistgov/ccu_validation_scoring#2]
Tried installing via:
`pip install git+https://github.com/usnistgov/ccu_validation_scoring.git`

But got:
> ERROR: Could not find a version that satisfies the requirement subprocess (from ccu-validation-scoring)
> ERROR: No matching distribution found for subprocess

**Comment by jfiscus** [comment]
If you did not find a work around, the problem was fixed by https://github.com/usnistgov/ccu_validation_scoring/commit/6f1a1eebe38dd38dc9837fd0049d1eacaff13d8d. I will close this issue in week or so.
