### ISSUE TITLE
Typo in CCU_validation_scoring/__init__.py

### ISSUE THREAD

**Issue by amith-ananthram** [usnistgov/ccu_validation_scoring#4]
```preprocess_referece``` should be ```preprocess_reference```; happy to push a PR to correct though I don't think I have the right permissions!

**Comment by jfiscus** [comment]
Thanks, fixed in commit 340ae46814bd871de829f81d255ca30497a2a0e6

**Comment by amith-ananthram** [comment]
thank you!
