### ISSUE TITLE
Possible bug in score_tad

### ISSUE THREAD

**Issue by islam-nassar** [usnistgov/ccu_validation_scoring#6]
Seems there is a typo in [L761](https://github.com/usnistgov/ccu_validation_scoring/blob/0f9757db83e203520a6ccfc25655dfb84e2aa9fd/CCU_validation_scoring/score_norm_emotion.py#L761)

graph is spelt grqph..

**Comment by jfiscus** [comment]
Fixed in commit c673053fbe2da4b261a9e401c03e1753ec479066.
