### ISSUE TITLE
Potential bug in score_norm_emotion

### ISSUE THREAD

**Issue by islam-nassar** [usnistgov/ccu_validation_scoring#8]
This [line](https://github.com/usnistgov/ccu_validation_scoring/blob/5d3976ae56bb079637e02ca8c8eec1b161c0a9d9/CCU_validation_scoring/score_norm_emotion.py#L234) will throw an error if system submission has a specific emotion for any given file_id which does not exist in the reference annotations for that file. This is because there is no `status` in the emotion case.

**Comment by jfiscus** [comment]
Thanks for the bug report.  Fixed with commit fff43cfea48b5683fab53f0b2e1a521f9d0e93b5.
